-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 17:59:25 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(31) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  UNIQUE INDEX (`email` ASC),
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guild`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`guild` ;

CREATE TABLE IF NOT EXISTS `mydb`.`guild` (
  `gid` INT NOT NULL AUTO_INCREMENT,
  `g_name` VARCHAR(45) NOT NULL,
  `leader_id` INT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`gid`),
  INDEX `fk_guild_user1_idx` (`leader_id` ASC),
  CONSTRAINT `fk_guild_user1`
    FOREIGN KEY (`leader_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`party` ;

CREATE TABLE IF NOT EXISTS `mydb`.`party` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `gid` INT NOT NULL,
  `p_name` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `party_leader_id` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_party_guild1_idx` (`gid` ASC),
  INDEX `fk_party_user1_idx` (`party_leader_id` ASC),
  CONSTRAINT `fk_party_guild1`
    FOREIGN KEY (`gid`)
    REFERENCES `mydb`.`guild` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_party_user1`
    FOREIGN KEY (`party_leader_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`todo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`todo` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `assigner_id` INT NOT NULL,
  `pid` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `contents` VARCHAR(511) NULL,
  `duedate` DATETIME NULL,
  `completed` TINYINT NOT NULL,
  `last_editer_id` INT NOT NULL,
  PRIMARY KEY (`tid`),
  INDEX `fk_todo_user_idx` (`assigner_id` ASC),
  INDEX `fk_todo_party1_idx` (`pid` ASC),
  INDEX `fk_todo_user1_idx` (`last_editer_id` ASC),
  CONSTRAINT `fk_todo_user`
    FOREIGN KEY (`assigner_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_party1`
    FOREIGN KEY (`pid`)
    REFERENCES `mydb`.`party` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_user1`
    FOREIGN KEY (`last_editer_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_guild_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_guild_relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_guild_relation` (
  `uid` INT NOT NULL,
  `gid` INT NOT NULL,
  `state` CHAR(2) NOT NULL DEFAULT 'G' COMMENT 'M, E, G',
  PRIMARY KEY (`uid`, `gid`),
  INDEX `fk_user_has_guild_guild1_idx` (`gid` ASC),
  INDEX `fk_user_has_guild_user1_idx` (`uid` ASC),
  CONSTRAINT `fk_user_has_guild_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_guild_guild1`
    FOREIGN KEY (`gid`)
    REFERENCES `mydb`.`guild` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_party_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_party_relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_party_relation` (
  `uid` INT NOT NULL,
  `pid` INT NOT NULL,
  `state` CHAR(2) NOT NULL DEFAULT 'G' COMMENT 'M, E, G',
  PRIMARY KEY (`uid`, `pid`),
  INDEX `fk_user_has_party_party1_idx` (`pid` ASC),
  INDEX `fk_user_has_party_user1_idx` (`uid` ASC),
  CONSTRAINT `fk_user_has_party_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_party_party1`
    FOREIGN KEY (`pid`)
    REFERENCES `mydb`.`party` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`content` ;

CREATE TABLE IF NOT EXISTS `mydb`.`content` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`content_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`content_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`content_history` (
  `hid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `contents` VARCHAR(511) NULL DEFAULT NULL,
  `duedate` DATETIME NULL DEFAULT NULL,
  `completed` TINYINT NOT NULL DEFAULT 0,
  `edited_time` TIMESTAMP NOT NULL,
  `flag` TINYINT NOT NULL DEFAULT 0 COMMENT 'edited or deleted',
  `tid` INT NOT NULL,
  `editer_id` INT NOT NULL,
  PRIMARY KEY (`hid`),
  INDEX `fk_content_history_todo1_idx` (`tid` ASC),
  INDEX `fk_content_history_user1_idx` (`editer_id` ASC),
  CONSTRAINT `fk_content_history_todo1`
    FOREIGN KEY (`tid`)
    REFERENCES `mydb`.`todo` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_history_user1`
    FOREIGN KEY (`editer_id`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`todo_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`todo_user_relation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`todo_user_relation` (
  `tid` INT NOT NULL,
  `uid` INT NOT NULL,
  PRIMARY KEY (`tid`, `uid`),
  INDEX `fk_todo_has_user_user1_idx` (`uid` ASC),
  INDEX `fk_todo_has_user_todo1_idx` (`tid` ASC),
  CONSTRAINT `fk_todo_has_user_todo1`
    FOREIGN KEY (`tid`)
    REFERENCES `mydb`.`todo` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_has_user_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `mydb`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
